name: Demo default variables
on:
 workflow_dispatch

jobs:
 print-default-vars:
  runs-on: ubuntu-latest
  steps:
   - run: |
      echo "$GITHUB_REF"
      echo "${GITHUB_REF_NAME}"
      echo "$GITHUB_TRIGGERING_ACTOR"
      echo "$GITHUB_ACTOR"
      echo ${{fromJSON(job)}}
